export const FormIds = {
  InviteParticipant: "addParticipantForm",
  EditParticipant: "editParticipantForm",
  AcceptInvite: "acceptInviteForm",
  RejectInvite: "rejectInviteForm",
  AddClassroom: "createClassroomForm",
  AddAssignment: "addAssignmentForm",
  AddQuestion: "addQuestionForm",
  AddFile: "addFileForm",
  EditFile: "editFileForm",
  EditClassroom: "editClassroomForm",
  EditAssignment: "editAssignmentForm",
  EditQuestion: "editQuestionForm",
  RenameConversation: "renameConversationForm",
} as const;
