import Head from "next/head";
import { SigninFormComponent as SigninForm } from "./SigninForm";
import { redirectLoggedInUserToHome } from "@/utils/redirectLoggedInUserToHome";

export default async function Signin() {
  await redirectLoggedInUserToHome();

  return (
    <>
      <Head>
        <title>Capstone Project: Signin</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SigninForm />
      </main>
    </>
  );
}
