import Head from "next/head";
import { LoginFormComponent as LoginForm } from "@/components/LoginForm";

export default function Login() {
  return (
    <>
      <Head>
        <title>ScholarSpace AI: Login</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <LoginForm />
      </main>
    </>
  );
}
