import Head from "next/head";
import { SignupFormComponent as SignupForm } from "./SignupForm";
import { redirectLoggedInUserToHome } from "@/utils/redirectLoggedInUserToHome";

export default async function Signup() {
  await redirectLoggedInUserToHome();

  return (
    <>
      <Head>
        <title>Capstone Project: Signup</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignupForm />
      </main>
    </>
  );
}
